# Generated by Django 5.2.12 on 2026-04-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crianca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome Completo da Criança')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('foto', models.ImageField(upload_to='fotos_3x4/', verbose_name='Foto 3x4')),
                ('nome_responsavel', models.CharField(max_length=200, verbose_name='Nome Completo do Responsável')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone para Recados')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Criança',
                'verbose_name_plural': 'Crianças',
            },
        ),
    ]
