# Generated by Django 5.2.12 on 2026-04-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crianca',
            name='telefone_alternativo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Alternativo (WhatsApp)'),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='telefone',
            field=models.CharField(max_length=20, verbose_name='Telefone Principal (WhatsApp)'),
        ),
    ]
